### ISSUE TITLE
Curl error after vanilla install

### ISSUE THREAD

**Issue by konklone** [bramus/mixed-content-scan#12]
I:

* installed the `php5` in Debian Jessie (which installs a `php` command)
* installed Composer using the global method (`curl` to a local `.phar` file, copy that `.phar` file to `/usr/local/bin/composer`)
* installed `mixed-content-scan` through the command on the README
* noticed that `mixed-content-scan` was not in my `$PATH`, and so added `$HOME/.composer/vendor/bin` to my `$PATH`

And then ran:

```bash
mixed-content-scan https://18f.gsa.gov
```

And got this error:

```
PHP Fatal error:  Call to undefined function Bramus\MCS\curl_init() in /home/eric/.composer/vendor/bramus/mixed-content-scan/src/Scanner.php on line 319

Fatal error: Call to undefined function Bramus\MCS\curl_init() in /home/eric/.composer/vendor/bramus/mixed-content-scan/src/Scanner.php on line 319
```

**Comment by bramus** [comment]
Hi Eric,

You must enable the curl extension in PHP. Otherwise it won't work. I'll look into adding a check which checks this prerequisite. 

Regards,
Bram.

**Comment by konklone** [comment]
Ah, that was it -- in Debian, I had to `apt-get install php5-curl`, and then everything worke.d

**Comment by bramus** [comment]
Glad to here it is solved now. Leaving this issue open until I put in the check.
Feel free to open a new ticket in case you encounter any other issues.
