### ISSUE TITLE
Support a sitemap input file option

### ISSUE THREAD

**Issue by konklone** [bramus/mixed-content-scan#15]
Instead of a crawl over outbound links, if the site has a full sitemap, it'd be nice to hand it to `mixed-content-scan` to walk over. This requires the scanner to read the (pretty light-weight) sitemap standard (the way I think it reads RSS feeds currently).

Sitemaps can often be gzipped, so it'd be nice to either have it be able to unzip sitemaps, or to provide a path to a downloaded file as the input (so I can download and unzip myself).

**Comment by bramus** [comment]
You can pass the sitemap URL into `mixed-content-scan` directly: `$ mixed-content-scan http://domain.tld/sitemap.url`.

Inside the MCS core there already is an option available to disable crawling, yet it is not exposed on the CLI yet. In https://github.com/bramus/mixed-content-scan/issues/9#issuecomment-66760872 it was suggested to use a `--no-crawl` option for this.

**Comment by konklone** [comment]
I tried feeding `mixed-content-scan` a URL to [a sitemap](https://konklone.com/sitemap/sitemap.xml) directly, but it did not pick out the links from the sitemap and walk them:

```
$ ./bin/mixed-content-scan https://konklone.com/sitemap/sitemap.xml

[2015-02-06 14:35:51] MCS.NOTICE: Scanning https://konklone.com/sitemap/sitemap.xml/ [] []
[2015-02-06 14:35:51] MCS.INFO: 00000 - https://konklone.com/sitemap/sitemap.xml/ [] []
[2015-02-06 14:35:51] MCS.NOTICE: Scanned 1 pages for Mixed Content [] []
```

**Comment by bramus** [comment]
Ah, you're talking about a true XML sitemap. That indeed won't work, as it uses other elements than HTML.

This makes this issue heavily linked to #9: instead of passing in a plaintext file (with one link per line) via the (suggested) `--input-file` option, one would pass in an XML in a likewise fashion.

**Comment by konklone** [comment]
Yeah, that sounds right to me. I've renamed the ticket to describe what we've arrived at. 

However, if #9 were implemented, I could imagine a sitemap->list-of-links step that could happen outside of this library and resolve the problem as well.

**Comment by bramus** [comment]
Splitting off the XML conversion to a list of links was also something I was thinking towards _(Separation of Concerns)_. 

#9 is on the todolist. I'll look into tackling it later this weekend / early next week.

I'll close this issue as the first hit on Google for "convert sitemap.xml to url list" points me towards http://www.hashbangcode.com/blog/convert-sitemapxml-file-urllisttxt-file-using-php, which should do the job.
