### ISSUE TITLE
Succesfully installed, but `mixed-content-scan` command is not recognized

### ISSUE THREAD

**Issue by vionemc** [bramus/mixed-content-scan#20]
This is what I have tried so far and the log of the result.

```
C:\Users\Ami>composer global require bramus/mixed-content-scan ~2.1
Changed current directory to C:/Users/Ami/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

C:\Users\Ami>SET PATH=~/.composer/vendor/bin

C:\Users\Ami>mixed-content-scan https://www.bram.us/
'mixed-content-scan' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bramus** [comment]
Hi Aminah,

What is the output of `PATH` when you type that at the CLI?

It should contain `C:\Users\Ami\AppData\Roaming\Composer\vendor\bin`, where `mixed-content-scan` resides (which I guess it does not). You can find instructions on how to change your `PATH` variable at [http://www.computerhope.com/issues/ch000549.htm](http://www.computerhope.com/issues/ch000549.htm)

Regards,
Bram.

**Comment by vionemc** [comment]
Hi Bramus!

Thanks, that solves the problem!

I'll close this.

**Comment by ericandrewlewis** [comment]
This happened to me too.

I added a note about this in #29 to help steer users in the right direction.
