### ISSUE TITLE
Make sure you run `composer install` first, before running this scanner

### ISSUE THREAD

**Issue by astembjx** [bramus/mixed-content-scan#26]
Hello,

Your tool looks great and is just what I need. I am just having an issue running mixed-content-scan. I am using Ubuntu 15.04. I have installed mixed-content-scan using composer

Despite installing using composer I am getting the following error.

I get the error when I run:
php /home/astembjx/Downloads/mixed-content-scan-2.1.1/bin/mixed-content-scan https://www.tdbank.com

I have attempted to run mixed-content-scan  from several different locations

My composer.phar  is installed in /home/astembjx  with vendor dir a sub under that  /home/astembjx/vendor/composer.  I have gone as far as copying the mixed-content-scan dirs into the vendor dir.  

I have attempted set the paths several times (as seen below) sometimes leading to PHP commends not being recognized at which point I close and reopen the terminal and I am fine.

export PATH=$PATH:/home/astembjx/Downloads/mixed-content-scan-2.1.1/bin
export PATH=/home/astembjx/Downloads/mixed-content-scan-2.1.1/bin:${PATH}
export PATH= $PATH ~/.composer/vendor/bin

I was hoping you could provide some assistance.

Composer shows the following
astembjx@ubuntu:~$ php composer.phar show | grep mixed-content-scan
bramus/mixed-content-scan
spatie/mixed-content-scanner

Your assistance is much appreciated

**Comment by astembjx** [comment]
Thanks for the response

**Comment by bramus** [comment]
Hi @astembjx,

You say you have an error when running `php /home/astembjx/Downloads/mixed-content-scan-2.1.1/bin/mixed-content-scan https://www.tdbank.com`. Could you paste an error/exception log?

Regards,
Bramus.

**Comment by bramus** [comment]
Think I know what you were doing: you installed `mixed-content-scan` locally, not globally. It is recommended to install this one globally, using `composer global require ...` instead of `composer require ...`. Instructions can be found in the readme.
