### ISSUE TITLE
rel="shortlink"

### ISSUE THREAD

**Issue by GaryJones** [bramus/mixed-content-scan#44]
WordPress supports short links, of the form `<link rel="shortlink" href="https://gmj.to/q1">`, though this isn't specifically a WordPress-related issue.

While your readme says it supports `link[href][rel="stylesheet"]`, my quick check of the code suggests that the `rel` value is never actually checked.

In the case of  shortlinks, that's just an external reference to a potentially different site, and as such, doesn't introduce any new content on the site being tested. I don't think these should be flagged, like they currently are.

**Comment by bramus** [comment]
Hi @GaryJones,

Good catch, the value of `rel` indeed is not checked. Looking back at the commit history, it looks like this regression was introduced with the refactor in commit 34567ffdad0cdd91775a41dad70be41486458f71.

Regards,
Bram.

**Comment by GaryJones** [comment]
It looks like `rel="profile"`, as in `<link rel="profile" href="http://gmpg.org/xfn/11" />`, suffers the same problem.

**Comment by jamieburchell** [comment]
This might be over-complicating things, but here's an idea for better separation of concerns and to deal with these specific tag requirements:

Create a validator class per tag type. Each class would contain its own array of attributes to check in its class properties and its own specific logic and methods for determining if a tag contains a MC link. It could expose a single, public `getMixedContentURLs` method.

Each validator class would extend an abstract base class. The base class would implement a default `getMixedContentURLs` method (which is fine for most tags) and an empty `$attributes` array property, to be defined in each sub class. The logic for checking the URL string could also be in its own function, with a default implementation in the base class.

In most cases, a tag specific validator class would only need an `$attributes` array in its properties.

The tag validator class would take a single `DomElement` parameter in its constructor and sub classes could check the element's tag name is supported.

```
abstract class TagValidator
{
   protected $element;
   protected $attributes;
   protected $mcUrls;

   public function __construct(\DomElement $el)
   public function getMixedContentUrls()
   protected function checkUrl($url)
}

class LinkTagValidator extends TagValidator
{
   protected $attributes = ['href'];
}
```
