### ISSUE TITLE
Export scan result 

### ISSUE THREAD

**Issue by skynet** [bramus/mixed-content-scan#46]
Is it possible to export scan result with colored lines?

**Comment by bramus** [comment]
You can use [the `--output` option](https://github.com/bramus/mixed-content-scan#advanced-usage--cli-options) for this. E.g. `mixed-content-scan --output result.txt https://www.bram.us/`. 

All output, including the ANSI Escape Sequences that define the color and style, are stored into the defined output (run `cat result.txt` afterwards, you'll see).
