### ISSUE TITLE
Only home page URL scanned

### ISSUE THREAD

**Issue by GaryJones** [bramus/mixed-content-scan#48]
![screenshot 2016-11-30 12 17 23](https://cloud.githubusercontent.com/assets/88371/20752030/fe6f84fe-b6f6-11e6-95b9-2ba98340a82f.png)

When the home page of danielstrading.com is scanned, mixed-content-scan doesn't navigate any further, despite there being the full range of navigation menu links, and links in the page content too, to other pages.

When a sub-page is scanned, all of the sub-sub-pages are found (good).

Why is the scan of the home page not finding the other pages on this WordPress site?

**Comment by bramus** [comment]
Hi @GaryJones,

When dumping the results of `curl_exec()` _(the command which fetches the page contents)_ I've noticed that the webserver returns a 403 on the index page:

```
[2016-11-30 23:56:10] MCS.NOTICE: Scanning https://www.danielstrading.com/ [] []
string(5134) "HTTP/1.1 403 Forbidden
Date: Wed, 30 Nov 2016 22:56:10 GMT
Server: Apache
Last-Modified: Thu, 16 Oct 2014 13:20:58 GMT
ETag: "1321-5058a1e728280"
Accept-Ranges: bytes
Content-Length: 4897
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<title>Apache HTTP Server Test Page powered by CentOS</title>
		<meta http-equiv="Content-Type""...
```

I've been able to bypass/fix this by explicitly setting a User-Agent. Fix will be pushed in the next few minutes.

**Comment by bramus** [comment]
Fixed in `0593e458881f7595301e2ff99c66754d1318bfba`

**Comment by GaryJones** [comment]
Thanks for the quick fix.

One of my colleagues fiddled with the `.htaccess`, and managed to comment out something (I've not checked what) which then made it work (before your fix). We do have some security-related lines in there, and one will likely be to reject requests from clients with no user agent string. I'm not sure why this wasn't carried through for requests to subdomains but that's unrelated here.

I'll wait until my colleague has finished, and try with the updated string against the `.htaccess` we had before, to confirm the fix.

**Comment by bramus** [comment]
👍

**Comment by GaryJones** [comment]
Fix confirmed, thanks.
