### ISSUE TITLE
Does this work with angular/react

### ISSUE THREAD

**Issue by awebdeveloper** [bramus/mixed-content-scan#61]
Does this work with angular/react kind of websites

**Comment by bramus** [comment]
Hi @awebdeveloper,

`mixed-content-scan` works by traversing the HTML as it was returned from the server. It does not scan nor interpret/execute JavaScript (and CSS for that matter), so the answer to your question is "no".

To make `mixed-content-scan` work with your angular/react project, you could set up serverside rendering for it.

Regards,
Bramus.
