### ISSUE TITLE
mixed-content-scan: command not found

### ISSUE THREAD

**Issue by Andrej64** [bramus/mixed-content-scan#75]
Hello,
I installed composer and copied composer.phar to /usr/bin/ and used this command to install the scanner:
composer.phar global require bramus/mixed-content-scan:~2.8

When i ran:  mixed-content-scan https://www.bram.us/
 i get :  mixed-content-scan: command not found

I tried : composer.phar mixed-content-scan https://www.bram.us/
i get:
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "mixed-content-scan" is not defined.

**Comment by bramus** [comment]
Can you check the contents of your `PATH` environment variable? It should contain a reference to something like `$HOME/.composer/vendor/bin"`

Assuming you're on Linux/macOS: Run `echo $PATH` on the CLI and check for the presence of `/.composer/vendor/bin`. If that's not the case, then adjust your `.bash_profile` by adding this line to it:

```
export PATH="$HOME/.composer/vendor/bin:$PATH"
```

After having added that line and saving said file run `source ~/.bash_profile` or start a new shell. From there on it should work.

**Comment by GainfulShrimp** [comment]
Although this is closed, I found it via a search engine when I had a similar issue, so thought I'd update with my findings.

My problem: I installed Composer fine (globally) and the output of `composer diagnose` all looked good too, but when I tried the `mixed-content-scan` command, I got "command not found" errors like the OP.

To resolve, I used the following command to identify the location of my 'vendor binaries' folder:

```
composer global config bin-dir --absolute
```

Then I used the result to work out what to add to my `$PATH` as @bramus suggested. In my case, I needed to add:

```
$HOME/.config/composer/vendor/bin
```

For more info, please see [the Composer docs](https://getcomposer.org/doc/03-cli.md#global) on the subject.
