### ISSUE TITLE
Colorized output

### ISSUE THREAD

**Issue by mathiasbynens** [bramus/mixed-content-scan#8]
Just some random ideas:
- [x] Highlight errors in red?
- [ ] Possibly add a `-q` / `--quiet` option that only prints “errors” i.e. entries with mixed content?

**Comment by bramus** [comment]
bramus/monolog-colored-line-formatter#1 got fixed + dependencies here were updated to use that new version (`95206e37a6dfcc1971028696a1b3f866693c9632`)
