### ISSUE TITLE
Use logfile instead of crawling

### ISSUE THREAD

**Issue by NoodlesNZ** [bramus/mixed-content-scan#9]
Is it possible to use a logfile to generate a list of URLs to scan. Our site is quite big and crawlers usually get stuck, so using an Apache access log to identify the most popular URLs would be a better way.

**Comment by konklone** [comment]
What's the simplest way to do CLI option parsing in PHP these days?

**Comment by bramus** [comment]
One that would seem feasible to me is https://github.com/pwfisher/CommandLine.php as it only does the parsing, and doesn't enforce a full app structure.

https://github.com/wp-cli/php-cli-tools also sports an arguments parser that looks like a nice option.

**Comment by bramus** [comment]
Eventually went with https://github.com/vanilla/garden-cli for the CLI option/argument parsing.
